// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/cyberday.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistroProductorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroProductorRequest) Reset() {
	*x = RegistroProductorRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroProductorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroProductorRequest) ProtoMessage() {}

func (x *RegistroProductorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroProductorRequest.ProtoReflect.Descriptor instead.
func (*RegistroProductorRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{0}
}

func (x *RegistroProductorRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type RegistroNodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Direccion     string                 `protobuf:"bytes,2,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroNodoRequest) Reset() {
	*x = RegistroNodoRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroNodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroNodoRequest) ProtoMessage() {}

func (x *RegistroNodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroNodoRequest.ProtoReflect.Descriptor instead.
func (*RegistroNodoRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{1}
}

func (x *RegistroNodoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *RegistroNodoRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type RegistroConsumidorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumidorId  string                 `protobuf:"bytes,1,opt,name=consumidor_id,json=consumidorId,proto3" json:"consumidor_id,omitempty"`
	Categorias    []string               `protobuf:"bytes,2,rep,name=categorias,proto3" json:"categorias,omitempty"`
	Tiendas       []string               `protobuf:"bytes,3,rep,name=tiendas,proto3" json:"tiendas,omitempty"`
	PrecioMax     int32                  `protobuf:"varint,4,opt,name=precio_max,json=precioMax,proto3" json:"precio_max,omitempty"`
	Direccion     string                 `protobuf:"bytes,5,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroConsumidorRequest) Reset() {
	*x = RegistroConsumidorRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroConsumidorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroConsumidorRequest) ProtoMessage() {}

func (x *RegistroConsumidorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroConsumidorRequest.ProtoReflect.Descriptor instead.
func (*RegistroConsumidorRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{2}
}

func (x *RegistroConsumidorRequest) GetConsumidorId() string {
	if x != nil {
		return x.ConsumidorId
	}
	return ""
}

func (x *RegistroConsumidorRequest) GetCategorias() []string {
	if x != nil {
		return x.Categorias
	}
	return nil
}

func (x *RegistroConsumidorRequest) GetTiendas() []string {
	if x != nil {
		return x.Tiendas
	}
	return nil
}

func (x *RegistroConsumidorRequest) GetPrecioMax() int32 {
	if x != nil {
		return x.PrecioMax
	}
	return 0
}

func (x *RegistroConsumidorRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type RegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistroResponse) Reset() {
	*x = RegistroResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroResponse) ProtoMessage() {}

func (x *RegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroResponse.ProtoReflect.Descriptor instead.
func (*RegistroResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{3}
}

func (x *RegistroResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type InicioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InicioRequest) Reset() {
	*x = InicioRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InicioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicioRequest) ProtoMessage() {}

func (x *InicioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicioRequest.ProtoReflect.Descriptor instead.
func (*InicioRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{4}
}

type InicioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inicio        bool                   `protobuf:"varint,1,opt,name=inicio,proto3" json:"inicio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InicioResponse) Reset() {
	*x = InicioResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InicioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InicioResponse) ProtoMessage() {}

func (x *InicioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InicioResponse.ProtoReflect.Descriptor instead.
func (*InicioResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{5}
}

func (x *InicioResponse) GetInicio() bool {
	if x != nil {
		return x.Inicio
	}
	return false
}

type OfertaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfertaId      string                 `protobuf:"bytes,1,opt,name=oferta_id,json=ofertaId,proto3" json:"oferta_id,omitempty"`
	Tienda        string                 `protobuf:"bytes,2,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Categoria     string                 `protobuf:"bytes,3,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Producto      string                 `protobuf:"bytes,4,opt,name=producto,proto3" json:"producto,omitempty"`
	Precio        int32                  `protobuf:"varint,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Fecha         string                 `protobuf:"bytes,7,opt,name=fecha,proto3" json:"fecha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfertaRequest) Reset() {
	*x = OfertaRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaRequest) ProtoMessage() {}

func (x *OfertaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaRequest.ProtoReflect.Descriptor instead.
func (*OfertaRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{6}
}

func (x *OfertaRequest) GetOfertaId() string {
	if x != nil {
		return x.OfertaId
	}
	return ""
}

func (x *OfertaRequest) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *OfertaRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *OfertaRequest) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *OfertaRequest) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *OfertaRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *OfertaRequest) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

type OfertaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfertaResponse) Reset() {
	*x = OfertaResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfertaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfertaResponse) ProtoMessage() {}

func (x *OfertaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfertaResponse.ProtoReflect.Descriptor instead.
func (*OfertaResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{7}
}

func (x *OfertaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

//********* Mensajes para sincronizacion de nodos **********
type SincronizacionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntidadId       string                 `protobuf:"bytes,1,opt,name=entidad_id,json=entidadId,proto3" json:"entidad_id,omitempty"`
	Tipo            string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	OfertasActuales []*OfertaRequest       `protobuf:"bytes,3,rep,name=ofertas_actuales,json=ofertasActuales,proto3" json:"ofertas_actuales,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SincronizacionRequest) Reset() {
	*x = SincronizacionRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizacionRequest) ProtoMessage() {}

func (x *SincronizacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizacionRequest.ProtoReflect.Descriptor instead.
func (*SincronizacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{8}
}

func (x *SincronizacionRequest) GetEntidadId() string {
	if x != nil {
		return x.EntidadId
	}
	return ""
}

func (x *SincronizacionRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *SincronizacionRequest) GetOfertasActuales() []*OfertaRequest {
	if x != nil {
		return x.OfertasActuales
	}
	return nil
}

type SincronizacionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OfertasFaltantes []*OfertaRequest       `protobuf:"bytes,1,rep,name=ofertas_faltantes,json=ofertasFaltantes,proto3" json:"ofertas_faltantes,omitempty"`
	Exito            bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SincronizacionResponse) Reset() {
	*x = SincronizacionResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SincronizacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SincronizacionResponse) ProtoMessage() {}

func (x *SincronizacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SincronizacionResponse.ProtoReflect.Descriptor instead.
func (*SincronizacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{9}
}

func (x *SincronizacionResponse) GetOfertasFaltantes() []*OfertaRequest {
	if x != nil {
		return x.OfertasFaltantes
	}
	return nil
}

func (x *SincronizacionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

//******** Mensajes para lectura **********
type LecturaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LecturaRequest) Reset() {
	*x = LecturaRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LecturaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LecturaRequest) ProtoMessage() {}

func (x *LecturaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LecturaRequest.ProtoReflect.Descriptor instead.
func (*LecturaRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{10}
}

type LecturaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ofertas       []*OfertaRequest       `protobuf:"bytes,1,rep,name=ofertas,proto3" json:"ofertas,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LecturaResponse) Reset() {
	*x = LecturaResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LecturaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LecturaResponse) ProtoMessage() {}

func (x *LecturaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LecturaResponse.ProtoReflect.Descriptor instead.
func (*LecturaResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{11}
}

func (x *LecturaResponse) GetOfertas() []*OfertaRequest {
	if x != nil {
		return x.Ofertas
	}
	return nil
}

func (x *LecturaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

//******** Mensajes para Shutdown **********
type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	mi := &file_proto_cyberday_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{12}
}

type ConsultarEstadoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activo        bool                   `protobuf:"varint,1,opt,name=activo,proto3" json:"activo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	mi := &file_proto_cyberday_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberday_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberday_proto_rawDescGZIP(), []int{13}
}

func (x *ConsultarEstadoResponse) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

var File_proto_cyberday_proto protoreflect.FileDescriptor

const file_proto_cyberday_proto_rawDesc = "" +
	"\n" +
	"\x14proto/cyberday.proto\x12\bcyberday\"2\n" +
	"\x18RegistroProductorRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\"K\n" +
	"\x13RegistroNodoRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tdireccion\x18\x02 \x01(\tR\tdireccion\"\xb7\x01\n" +
	"\x19RegistroConsumidorRequest\x12#\n" +
	"\rconsumidor_id\x18\x01 \x01(\tR\fconsumidorId\x12\x1e\n" +
	"\n" +
	"categorias\x18\x02 \x03(\tR\n" +
	"categorias\x12\x18\n" +
	"\atiendas\x18\x03 \x03(\tR\atiendas\x12\x1d\n" +
	"\n" +
	"precio_max\x18\x04 \x01(\x05R\tprecioMax\x12\x1c\n" +
	"\tdireccion\x18\x05 \x01(\tR\tdireccion\"(\n" +
	"\x10RegistroResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\"\x0f\n" +
	"\rInicioRequest\"(\n" +
	"\x0eInicioResponse\x12\x16\n" +
	"\x06inicio\x18\x01 \x01(\bR\x06inicio\"\xc2\x01\n" +
	"\rOfertaRequest\x12\x1b\n" +
	"\toferta_id\x18\x01 \x01(\tR\bofertaId\x12\x16\n" +
	"\x06tienda\x18\x02 \x01(\tR\x06tienda\x12\x1c\n" +
	"\tcategoria\x18\x03 \x01(\tR\tcategoria\x12\x1a\n" +
	"\bproducto\x18\x04 \x01(\tR\bproducto\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05fecha\x18\a \x01(\tR\x05fecha\"&\n" +
	"\x0eOfertaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\"\x8e\x01\n" +
	"\x15SincronizacionRequest\x12\x1d\n" +
	"\n" +
	"entidad_id\x18\x01 \x01(\tR\tentidadId\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12B\n" +
	"\x10ofertas_actuales\x18\x03 \x03(\v2\x17.cyberday.OfertaRequestR\x0fofertasActuales\"t\n" +
	"\x16SincronizacionResponse\x12D\n" +
	"\x11ofertas_faltantes\x18\x01 \x03(\v2\x17.cyberday.OfertaRequestR\x10ofertasFaltantes\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\"\x10\n" +
	"\x0eLecturaRequest\"Z\n" +
	"\x0fLecturaResponse\x121\n" +
	"\aofertas\x18\x01 \x03(\v2\x17.cyberday.OfertaRequestR\aofertas\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\"\x18\n" +
	"\x16ConsultarEstadoRequest\"1\n" +
	"\x17ConsultarEstadoResponse\x12\x16\n" +
	"\x06activo\x18\x01 \x01(\bR\x06activo2\x89\x05\n" +
	"\x0fCyberDayService\x12T\n" +
	"\x12RegistrarProductor\x12\".cyberday.RegistroProductorRequest\x1a\x1a.cyberday.RegistroResponse\x12J\n" +
	"\rRegistrarNodo\x12\x1d.cyberday.RegistroNodoRequest\x1a\x1a.cyberday.RegistroResponse\x12V\n" +
	"\x13RegistrarConsumidor\x12#.cyberday.RegistroConsumidorRequest\x1a\x1a.cyberday.RegistroResponse\x12D\n" +
	"\x0fSolicitarInicio\x12\x17.cyberday.InicioRequest\x1a\x18.cyberday.InicioResponse\x12A\n" +
	"\fEnviarOferta\x12\x17.cyberday.OfertaRequest\x1a\x18.cyberday.OfertaResponse\x12W\n" +
	"\x12SincronizarEntidad\x12\x1f.cyberday.SincronizacionRequest\x1a .cyberday.SincronizacionResponse\x12B\n" +
	"\vLeerOfertas\x12\x18.cyberday.LecturaRequest\x1a\x19.cyberday.LecturaResponse\x12V\n" +
	"\x0fConsultarEstado\x12 .cyberday.ConsultarEstadoRequest\x1a!.cyberday.ConsultarEstadoResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_cyberday_proto_rawDescOnce sync.Once
	file_proto_cyberday_proto_rawDescData []byte
)

func file_proto_cyberday_proto_rawDescGZIP() []byte {
	file_proto_cyberday_proto_rawDescOnce.Do(func() {
		file_proto_cyberday_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)))
	})
	return file_proto_cyberday_proto_rawDescData
}

var file_proto_cyberday_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_cyberday_proto_goTypes = []any{
	(*RegistroProductorRequest)(nil),  // 0: cyberday.RegistroProductorRequest
	(*RegistroNodoRequest)(nil),       // 1: cyberday.RegistroNodoRequest
	(*RegistroConsumidorRequest)(nil), // 2: cyberday.RegistroConsumidorRequest
	(*RegistroResponse)(nil),          // 3: cyberday.RegistroResponse
	(*InicioRequest)(nil),             // 4: cyberday.InicioRequest
	(*InicioResponse)(nil),            // 5: cyberday.InicioResponse
	(*OfertaRequest)(nil),             // 6: cyberday.OfertaRequest
	(*OfertaResponse)(nil),            // 7: cyberday.OfertaResponse
	(*SincronizacionRequest)(nil),     // 8: cyberday.SincronizacionRequest
	(*SincronizacionResponse)(nil),    // 9: cyberday.SincronizacionResponse
	(*LecturaRequest)(nil),            // 10: cyberday.LecturaRequest
	(*LecturaResponse)(nil),           // 11: cyberday.LecturaResponse
	(*ConsultarEstadoRequest)(nil),    // 12: cyberday.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil),   // 13: cyberday.ConsultarEstadoResponse
}
var file_proto_cyberday_proto_depIdxs = []int32{
	6,  // 0: cyberday.SincronizacionRequest.ofertas_actuales:type_name -> cyberday.OfertaRequest
	6,  // 1: cyberday.SincronizacionResponse.ofertas_faltantes:type_name -> cyberday.OfertaRequest
	6,  // 2: cyberday.LecturaResponse.ofertas:type_name -> cyberday.OfertaRequest
	0,  // 3: cyberday.CyberDayService.RegistrarProductor:input_type -> cyberday.RegistroProductorRequest
	1,  // 4: cyberday.CyberDayService.RegistrarNodo:input_type -> cyberday.RegistroNodoRequest
	2,  // 5: cyberday.CyberDayService.RegistrarConsumidor:input_type -> cyberday.RegistroConsumidorRequest
	4,  // 6: cyberday.CyberDayService.SolicitarInicio:input_type -> cyberday.InicioRequest
	6,  // 7: cyberday.CyberDayService.EnviarOferta:input_type -> cyberday.OfertaRequest
	8,  // 8: cyberday.CyberDayService.SincronizarEntidad:input_type -> cyberday.SincronizacionRequest
	10, // 9: cyberday.CyberDayService.LeerOfertas:input_type -> cyberday.LecturaRequest
	12, // 10: cyberday.CyberDayService.ConsultarEstado:input_type -> cyberday.ConsultarEstadoRequest
	3,  // 11: cyberday.CyberDayService.RegistrarProductor:output_type -> cyberday.RegistroResponse
	3,  // 12: cyberday.CyberDayService.RegistrarNodo:output_type -> cyberday.RegistroResponse
	3,  // 13: cyberday.CyberDayService.RegistrarConsumidor:output_type -> cyberday.RegistroResponse
	5,  // 14: cyberday.CyberDayService.SolicitarInicio:output_type -> cyberday.InicioResponse
	7,  // 15: cyberday.CyberDayService.EnviarOferta:output_type -> cyberday.OfertaResponse
	9,  // 16: cyberday.CyberDayService.SincronizarEntidad:output_type -> cyberday.SincronizacionResponse
	11, // 17: cyberday.CyberDayService.LeerOfertas:output_type -> cyberday.LecturaResponse
	13, // 18: cyberday.CyberDayService.ConsultarEstado:output_type -> cyberday.ConsultarEstadoResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_cyberday_proto_init() }
func file_proto_cyberday_proto_init() {
	if File_proto_cyberday_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberday_proto_rawDesc), len(file_proto_cyberday_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cyberday_proto_goTypes,
		DependencyIndexes: file_proto_cyberday_proto_depIdxs,
		MessageInfos:      file_proto_cyberday_proto_msgTypes,
	}.Build()
	File_proto_cyberday_proto = out.File
	file_proto_cyberday_proto_goTypes = nil
	file_proto_cyberday_proto_depIdxs = nil
}
